group: travis_latest
sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - pip install --upgrade pip setuptools
  - pip install flake8 requests setproctitle youtube-dl 

addons:
  apt:
    packages:
    - aria2
    - sound-theme-freedesktop
    - libnotify-bin
    - libqt5svg5
    - python3-pyqt5
    - python3-pyqt5.qtsvg
    - pulseaudio

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

script:
 - sudo python3 setup.py install
 - persepolis --version

after_success:
 - pip install transifex-client==0.12.5
 - sudo echo $'[https://www.transifex.com]\napi_hostname = https://api.transifex.com\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\n' > ~/.transifexrc
 - tx push -s
